apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    name: auth-sdc
    namespace: streamsets
  spec:
    rules:
    - host: minikube.sdc
      http:
        paths:
        - path: /
          backend:
            serviceName: auth-sdc
            servicePort: 18630
