# Default values for Streamsets Control Agent
image:
  repository: streamsets/control-agent
  tag: latest
  pullPolicy: Always
streamsets:
  orgId: dpmsupport
  crdEnabled: false
  api:
    url: https://cloud.streamsets.com
    token: "NTg4N2E4MDUtYjg5Ni00MWZhLWI1ZjAtNTc5YTRmYTRiMDMy:Mjk0YjQ1MjZmZjAwZDMyZmJiZGJjODNjYzM3YWQyNjFiZTcyMzM3ZGMzMjk4ODkxZjUyMWY5YzJhZTEyNjUxNTA0NjJjODkwYjdjOGE4NDI1YjA5NWFiZTJiM2JkN2RmZDRhZjQ4NGIwZThmNjNhMDg3ZGYyMTA0MzZkZjkzMDI="
rbac:
  enabled: true
krb:
  enabled: false
  encryptionTypes: <encryption types to use when creating a keytab for service principal>
  containerDn: <distinguished name of the container under which new principals will be created>
  ldapUrl: <URL of the LDAP service provider>
  adminPrincipal: <user account which has privileges to create, search and destroy service principals>
  adminKey: <secret key for the above account>
  realm: <the realm of the organization>
  kdcType: < AD | MIT >
##
## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources: {}
nodeSelector: {}
